version: '3.4'

services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: My01pass # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: ownersandpets # The PostgreSQL default database (automatically created at first launch)
  
  #added volume part for database
  volumes:
    - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
  
  command-line:
    build:
     context: .
     dockerfile: Dockerfile
    command: tail -f /dev/null
    links: 
      - database
    volumes:
      - ..:/workspace
    